-- MySQL Script generated by MySQL Workbench
-- Wed Jul  1 09:22:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema test_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `test_db` ;

-- -----------------------------------------------------
-- Schema test_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `test_db` ;

-- -----------------------------------------------------
-- Table `test_db`.`table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_db`.`table` ;

CREATE TABLE IF NOT EXISTS `test_db`.`table` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `field1` VARCHAR(45) NOT NULL,
  `field2` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test_db`.`linktable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_db`.`linktable` ;

CREATE TABLE IF NOT EXISTS `test_db`.`linktable` (
  `id` INT(10) UNSIGNED NOT NULL,
  `field1` VARCHAR(20) NOT NULL,
  INDEX `fk_id_idx` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_id`
    FOREIGN KEY (`id`)
    REFERENCES `test_db`.`table` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
