[package]
<<<<<<< HEAD:rust/numerology-alg/Cargo.toml
name = "numerology-alg"
=======
name = "multiplication-table"
>>>>>>> f300c9d79793637ba34ea84c28c715f00cd18f0a:rust/multiplication-table/Cargo.toml
version = "0.1.0"
authors = ["youngtrashbag", "swag"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
